import React, {useEffect, useRef, useState} from 'react';
import {Alert, AppState, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View} from 'react-native';
import {SafeAreaProvider, SafeAreaView} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import * as Location from 'expo-location';
import {acceptTask, canReveal, seeds, tracks, transition} from './src/tasks.mjs';

type Task = typeof seeds[number] & {worker?:string; agreement?:{signature:string; signedAt:string; version:string; amount:number; scope:string}};
const money=(n:number)=>`₦${n.toLocaleString('en-NG')}`;
function Button({title,onPress,secondary=false,disabled=false}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.secondary,disabled&&{opacity:.45}]}><Text style={[s.buttonText,secondary&&{color:'#174C39'}]}>{title}</Text></Pressable>}
function Field({label,value,onChange,number=false,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;number?:boolean;multiline?:boolean}){return <View style={{gap:8}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} keyboardType={number?'numeric':'default'} multiline={multiline} style={[s.input,multiline&&{minHeight:90,textAlignVertical:'top'}]}/></View>}
export default function App(){
 const [tab,setTab]=useState('Find work'),[tasks,setTasks]=useState<Task[]>(seeds),[selected,setSelected]=useState<string|null>(null),[signature,setSignature]=useState(''),[consent,setConsent]=useState(false),[role,setRole]=useState('worker'),[filter,setFilter]=useState('All');
 const [title,setTitle]=useState(''),[area,setArea]=useState(''),[amount,setAmount]=useState(''),[scope,setScope]=useState(''),[duration,setDuration]=useState(''),[postConsent,setPostConsent]=useState(false);
 const [gps,setGps]=useState('No active task'),[retry,setRetry]=useState(0),[foreground,setForeground]=useState(AppState.currentState==='active');
 const [reviews,setReviews]=useState<{task:string;comment:string;rating:number}[]>([]),[comment,setComment]=useState(''),[rating,setRating]=useState(5);
 const watch=useRef<Location.LocationSubscription|null>(null);
 const actor=role==='worker'?'worker-demo':'customer-demo';
 const task=tasks.find(t=>t.id===selected);
 const active=tasks.find(t=>t.worker==='worker-demo'&&tracks(t));
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>setForeground(state==='active'));return()=>sub.remove()},[]);
 useEffect(()=>{
   let disposed=false;watch.current?.remove();watch.current=null;
   if(!active||role!=='worker'||!foreground){setGps(active?'Location paused — open the worker view':'Location sharing stopped');return;}
   setGps('Requesting location permission…');
   (async()=>{try{const permission=await Location.requestForegroundPermissionsAsync();if(disposed)return;if(permission.status!=='granted'){setGps('Location permission denied. Enable it in Android settings, then retry.');return;}
   const sub=await Location.watchPositionAsync({accuracy:Location.Accuracy.Balanced,timeInterval:10000,distanceInterval:20},p=>{if(!disposed)setGps(`Last fix ${new Date(p.timestamp).toLocaleTimeString()} · accuracy ±${Math.round(p.coords.accuracy??0)} m. Stored only in this session; not shared.`)},()=>{if(!disposed)setGps('Location unavailable. Check GPS and retry.');});if(disposed)sub.remove();else watch.current=sub;
   }catch{if(!disposed)setGps('Could not start GPS. Check device permissions and retry.')}})();
   return()=>{disposed=true;watch.current?.remove();watch.current=null;};
 },[active?.id,role,foreground,retry]);
 const replace=(updated:Task)=>setTasks(prev=>prev.map(t=>t.id===updated.id?updated:t));
 const move=(next:string)=>{if(!task)return;try{replace(transition(task,actor,next));}catch(e){Alert.alert('Cannot update task',String((e as Error).message));}};
 const close=()=>{setSelected(null);setConsent(false);setSignature('');setComment('');};
 const accept=()=>{if(!task)return;if(active){Alert.alert('Finish your active task first');return;}try{replace(acceptTask(task,actor,signature,consent,new Date().toISOString()));setTab('My tasks');}catch(e){Alert.alert('Cannot accept',String((e as Error).message));}};
 const post=()=>{const n=Number(amount);if(!title.trim()||!area.trim()||!scope.trim()||!duration.trim()||!Number.isFinite(n)||n<=0||!Number.isInteger(n)||!postConsent){Alert.alert('Complete the task details','Enter a whole-naira amount above zero and agree to the task terms.');return;}setTasks(prev=>[{id:Date.now().toString(),title:title.trim(),area:area.trim(),amount:n,description:scope.trim(),duration:duration.trim(),category:'General',owner:actor,status:'Open'},...prev]);setTitle('');setArea('');setAmount('');setScope('');setDuration('');setPostConsent(false);setTab('My tasks');};
 return <SafeAreaProvider><SafeAreaView style={s.root}><StatusBar style="dark"/><View style={s.header}><View><Text style={s.logo}>erranus<Text style={{color:'#A8CF43'}}>●</Text></Text><Text style={s.small}>Everyday work. Agreed pay.</Text></View><Pressable accessibilityRole="button" onPress={()=>{setRole(role==='worker'?'customer':'worker');setTab('My tasks')}} style={s.role}><Text style={s.label}>{role==='worker'?'Worker ⇄':'Customer ⇄'}</Text></Pressable></View>
 <View style={s.demo}><Text style={s.demoText}>LOCAL DEMO · Sample people · No real payments · Resets on restart</Text></View>
 <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 {tab==='Find work'&&<><Text style={s.eyebrow}>WORK OPPORTUNITIES</Text><Text style={s.heading}>Your next task,{ '\n'}closer to home.</Text><Text style={s.muted}>Explore sample jobs in Lagos. Know the work and the pay before you accept.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingVertical:10}}>{['All','Shop support','Cleaning','Events'].map(x=><Pressable accessibilityRole="button" accessibilityState={{selected:filter===x}} key={x} onPress={()=>setFilter(x)} style={[s.chip,filter===x&&s.chipOn]}><Text style={{color:filter===x?'white':'#365345',fontWeight:'600'}}>{x}</Text></Pressable>)}</ScrollView><Text style={s.section}>Available tasks</Text>{tasks.filter(t=>t.status==='Open'&&(filter==='All'||t.category===filter)).map(t=><Pressable accessibilityRole="button" accessibilityLabel={`View ${t.title}`} key={t.id} style={s.card} onPress={()=>setSelected(t.id)}><View style={s.row}><Text style={s.category}>{t.category}</Text><Text style={s.small}>{t.duration}</Text></View><Text style={s.taskTitle}>{t.title}</Text><Text style={s.muted}>{t.area}</Text><View style={[s.row,s.cardFoot]}><Text style={s.price}>{money(t.amount)}</Text><Text style={s.link}>View task →</Text></View></Pressable>)}<Text style={s.small}>Customer details unlock after signing and acceptance.</Text></>}
 {tab==='My tasks'&&<><Text style={s.eyebrow}>YOUR WORKSPACE</Text><Text style={s.heading}>My tasks</Text><Text style={s.muted}>{role==='worker'?'Work you have accepted.':'Tasks posted by your demo customer account.'}</Text>{tasks.filter(t=>role==='worker'?t.worker===actor:t.owner===actor).map(t=><Pressable accessibilityRole="button" key={t.id} style={s.card} onPress={()=>setSelected(t.id)}><Text style={s.category}>{t.status}</Text><Text style={s.taskTitle}>{t.title}</Text><Text style={s.price}>{money(t.amount)}</Text></Pressable>)}{!tasks.some(t=>role==='worker'?t.worker===actor:t.owner===actor)&&<View style={s.card}><Text style={s.taskTitle}>A fresh start</Text><Text style={s.muted}>{role==='worker'?'Accept a task to see your progress here.':'Post your first task to find a helping hand.'}</Text><Button title={role==='worker'?'Find work':'Post a task'} onPress={()=>setTab(role==='worker'?'Find work':'Post task')}/></View>}{active&&role==='worker'&&<View style={s.tracking}><Text style={s.section}>Task location</Text><Text style={s.muted}>{gps}</Text><Text style={s.small}>This demo reads GPS only while this worker view is open. Background tracking and customer sharing are not connected.</Text><Button secondary title="Retry GPS" onPress={()=>setRetry(v=>v+1)}/></View>}</>}
 {tab==='Post task'&&<><Text style={s.eyebrow}>GET A HELPING HAND</Text><Text style={s.heading}>What needs doing?</Text>{role!=='customer'?<View style={s.card}><Text style={s.muted}>Switch to your customer profile to post work.</Text><Button title="Use customer profile" onPress={()=>setRole('customer')}/></View>:<><Field label="Task title" value={title} onChange={setTitle}/><Field label="Public area (no exact address)" value={area} onChange={setArea}/><Field label="Pay in naira (₦)" value={amount} onChange={setAmount} number/><Field label="Expected duration" value={duration} onChange={setDuration}/><Field label="Work required and included expenses" value={scope} onChange={setScope} multiline/><View style={s.row}><Text style={[s.muted,{flex:1}]}>I agree to this scope and price. Any change requires both parties' approval.</Text><Switch accessibilityLabel="Agree to posted task terms" value={postConsent} onValueChange={setPostConsent}/></View><Button title="Post demo task" onPress={post}/></>}</>}
 {tab==='Profile'&&<><Text style={s.eyebrow}>YOUR PROFILE</Text><View style={s.avatar}><Text style={{fontSize:32,color:'white',fontWeight:'700'}}>{role==='worker'?'AO':'CU'}</Text></View><Text style={s.heading}>{role==='worker'?'Ada Okafor':'Customer account'}</Text><Text style={s.muted}>{role==='worker'?'Demo worker · Lagos, Nigeria':'Demo customer · Visible to assigned workers after agreement'}</Text><View style={s.card}><Text style={s.section}>{role==='worker'?'Skills & experience':'Profile visibility'}</Text><Text style={s.muted}>{role==='worker'?'Shop support · Cleaning · Event setup':'Your name and task address stay private until a worker accepts and signs. Real privacy requires the planned server access controls.'}</Text></View><Text style={s.section}>Reviews from completed tasks</Text>{reviews.length===0?<Text style={s.muted}>No reviews yet. Reviews become available after a completed job.</Text>:reviews.map(r=><View key={r.task} style={s.card}><Text style={s.category}>{'★'.repeat(r.rating)}</Text><Text style={s.muted}>{r.comment}</Text><Text style={s.small}>Demo review · Completed task</Text></View>)}</>}
 </ScrollView><View style={s.nav}>{['Find work','My tasks','Post task','Profile'].map((x,i)=><Pressable accessibilityRole="tab" accessibilityState={{selected:tab===x}} key={x} onPress={()=>setTab(x)} style={s.navItem}><Text style={{fontSize:21,color:tab===x?'#176044':'#76827C'}}>{['⌕','☷','＋','○'][i]}</Text><Text style={[s.small,tab===x&&s.link]}>{x}</Text></Pressable>)}</View>
 <Modal visible={!!task} animationType="slide" onRequestClose={close}><SafeAreaView style={s.root}><View style={s.header}><Text style={s.section}>Task details</Text><Button title="Close" secondary onPress={close}/></View>{task&&<ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.eyebrow}>{task.category} · {task.status}</Text><Text style={s.heading}>{task.title}</Text><Text style={s.muted}>{task.area} · {task.duration}</Text><Text style={s.price}>{money(task.amount)} agreed pay</Text><Text style={s.section}>The work</Text><Text style={s.muted}>{task.description}</Text><View style={s.card}><Text style={s.section}>{canReveal(task,actor)?'Customer profile unlocked':'Customer profile is private'}</Text><Text style={s.muted}>{canReveal(task,actor)?'Demo customer · This prototype contains no real contact details or exact addresses.':'You can see the customer’s details after accepting this task and signing the agreement.'}</Text></View>
 {task.status==='Open'&&role==='worker'&&<><Text style={s.section}>Your task agreement</Text><Text style={s.muted}>Complete the work described above for {money(task.amount)}. Do not ask for or collect unapproved extra payments from the customer or anyone involved. Changes to work or expenses require both parties to agree first.</Text><Text style={s.small}>Demo agreement v1 · The customer proposes these terms when posting. Final launch terms still need review.</Text><Field label="Type your full name to sign" value={signature} onChange={setSignature}/><View style={s.row}><Text style={[s.muted,{flex:1}]}>I accept these terms and consent to GPS collection during this task. This demo collects only while open and does not transmit my location.</Text><Switch accessibilityLabel="Accept agreement and GPS consent" value={consent} onValueChange={setConsent}/></View><Button title="Sign & accept task" onPress={accept} disabled={!consent||!signature.trim()||!!active}/>{!!active&&<Text style={s.small}>Finish or cancel your active task before accepting another.</Text>}</>}
 {task.agreement&&canReveal(task,actor)&&<Text style={s.small}>Signed by {task.agreement.signature} · {new Date(task.agreement.signedAt).toLocaleString()} · Agreement v{task.agreement.version}</Text>}
 {task.worker===actor&&tracks(task)&&<><View style={s.tracking}><Text style={s.section}>Location status</Text><Text style={s.muted}>{gps}</Text></View><Button title={task.status==='Accepted'?'Start work':'Request completion'} onPress={()=>move(task.status==='Accepted'?'In progress':'Completion requested')}/><Button secondary title="Cancel task" onPress={()=>Alert.alert('Cancel this task?','Location collection will stop.',[{text:'Keep task',style:'cancel'},{text:'Cancel task',style:'destructive',onPress:()=>move('Cancelled')}])}/></>}
 {task.status==='Completion requested'&&<><Text style={s.muted}>Work submitted. GPS collection has stopped. Waiting for customer confirmation.</Text>{task.owner===actor?<Button title="Confirm completion" onPress={()=>move('Completed')}/>:<Button secondary title="Simulate customer confirmation (demo)" onPress={()=>replace(transition(task,task.owner,'Completed'))}/>}</>}
 {task.status==='Completed'&&<><Text style={s.category}>Work completed · No payment processed in demo</Text>{!reviews.some(r=>r.task===task.id)&&<><Text style={s.section}>Try a completed-task review</Text><Text style={s.small}>Demo only: this previews a customer review on the worker profile.</Text><View style={s.row}>{[1,2,3,4,5].map(n=><Pressable key={n} accessibilityRole="button" accessibilityLabel={`${n} stars`} onPress={()=>setRating(n)}><Text style={{fontSize:32,color:n<=rating?'#986500':'#CCD2CC'}}>★</Text></Pressable>)}</View><Field label="Review comment" value={comment} onChange={setComment} multiline/><Button title="Save demo review" disabled={!comment.trim()} onPress={()=>{setReviews(prev=>[...prev,{task:task.id,comment:comment.trim(),rating}]);setComment('');}}/></>}</>}
 </ScrollView>}</SafeAreaView></Modal></SafeAreaView></SafeAreaProvider>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#F6F8F5'},header:{paddingHorizontal:22,paddingVertical:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{fontSize:32,fontWeight:'800',letterSpacing:-1.5,color:'#174C39'},small:{fontSize:12,lineHeight:18,color:'#647469'},label:{fontSize:14,fontWeight:'600',color:'#264335'},role:{padding:12,borderRadius:24,backgroundColor:'#E6EDDF'},demo:{backgroundColor:'#E9EFDF',paddingHorizontal:22,paddingVertical:9},demoText:{fontSize:12,color:'#425334',lineHeight:18},content:{padding:22,gap:18,paddingBottom:35},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:1.6,color:'#467451'},heading:{fontSize:34,lineHeight:39,fontWeight:'700',letterSpacing:-1,color:'#183D2D'},muted:{fontSize:16,lineHeight:25,color:'#526559'},section:{fontSize:19,fontWeight:'700',color:'#203E2D'},card:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#DFE7DC',borderRadius:18,padding:20,gap:13},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},category:{color:'#376843',fontSize:13,fontWeight:'700'},taskTitle:{fontSize:21,lineHeight:28,fontWeight:'600',color:'#203E2D'},cardFoot:{borderTopWidth:1,borderTopColor:'#EDF0E9',paddingTop:15,marginTop:3},price:{fontSize:23,fontWeight:'700',color:'#194932'},link:{color:'#176044',fontWeight:'700'},chip:{paddingHorizontal:19,paddingVertical:12,borderRadius:25,backgroundColor:'#E8EEE3'},chipOn:{backgroundColor:'#20583E'},button:{backgroundColor:'#20583E',paddingHorizontal:18,paddingVertical:15,borderRadius:12,alignItems:'center'},buttonText:{fontSize:16,fontWeight:'700',color:'white'},secondary:{backgroundColor:'#E8EEE3'},input:{borderWidth:1,borderColor:'#CBD7C8',backgroundColor:'#FFF',padding:14,borderRadius:12,fontSize:16,color:'#203E2D'},tracking:{backgroundColor:'#EAF0E2',padding:19,borderRadius:16,gap:12},nav:{flexDirection:'row',borderTopWidth:1,borderTopColor:'#DDE5D9',backgroundColor:'#FFF',paddingVertical:10},navItem:{flex:1,alignItems:'center',gap:4,paddingVertical:5},avatar:{height:85,width:85,borderRadius:43,backgroundColor:'#20583E',alignItems:'center',justifyContent:'center'}});
